# Dockerfile.dev
FROM node:24-alpine AS development

WORKDIR /usr/src/app

# 의존성 정의 파일 복사
COPY package*.json ./

# devDependencies(Nest CLI, TypeScript 등)를 모두 포함하여 패키지 설치
RUN npm ci

# 소스 코드 복사 (볼륨 마운트를 하더라도 최초 빌드 및 세팅을 위해 필요)
COPY . .

# 소스 코드 수정 감지(Watch)를 위해 포트 노출
EXPOSE 3000

# Nest.js 개발 모드 실행 (nest start --watch)
CMD ["npm", "run", "start:dev"]