server:
  port: 3000

db:
  type: 'postgres'
  host: ${SUPABASE_DB_HOST}
  port: ${SUPABASE_DB_PORT}
  username: ${SUPABASE_DB_USERNAME}
  password: ${SUPABASE_DB_PASSWORD}
  database: ${SUPABASE_DB_NAME}
  logging: false
  # synchronize: true

redis:
  url: ${UPSTASH_REDIS_URL}

jwt:
  accessSecret: 'my-secret'
  refreshSecret: 'refresh-secret'
  accessTokenExpiresIn: 750      # 보통 짧게 설정 (15분)
  refreshTokenExpiresIn: 604800  # 보통 길게 설정 (7일)

oauth:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
  github:
    clientId: ${GITHUB_CLIENT_ID}
    clientSecret: ${GITHUB_CLIENT_SECRET}