server:
  port: 3000

db:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'kevinj'
  password: '12345^'
  database: 'devdb'
  logging: true
  # synchronize: true

redis:
  host: 'localhost'
  port: 6379
  db: 

jwt:
  accessSecret: 'my-secret'
  refreshSecret: 'refresh-secret'
  accessTokenExpiresIn: 3600
  refreshTokenExpiresIn: 86400
  # accessTokenExpiresIn: 750      # 보통 짧게 설정 (15분)
  # refreshTokenExpiresIn: 604800  # 보통 길게 설정 (7일)

oauth:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
  github:
    clientId: ${GITHUB_CLIENT_ID}
    clientSecret: ${GITHUB_CLIENT_SECRET}