server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'templates'

jwt:
 accessTokenExpiresIn: 750      # 보통 짧게 설정 (15분)
 refreshTokenExpiresIn: 604800  # 보통 길게 설정 (7일)

oauth:
  google:
    clientId: ""
    clientSecret: ""
  github:
    clientId: ""
    clientSecret: ""